# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: true
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/aws-sdk-kms/all/aws-sdk-kms.rbi
#
# aws-sdk-kms-1.24.0
module Aws::KMS
end
module Aws::KMS::Types
end
class Anonymous_Struct_183 < Struct
  def alias_arn; end
  def alias_arn=(_); end
  def alias_name; end
  def alias_name=(_); end
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
  def target_key_id; end
  def target_key_id=(_); end
end
class Aws::KMS::Types::AliasListEntry < Anonymous_Struct_183
  include Aws::Structure
end
class Anonymous_Struct_184 < Struct
  def message; end
  def message=(_); end
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
end
class Aws::KMS::Types::AlreadyExistsException < Anonymous_Struct_184
  include Aws::Structure
end
class Anonymous_Struct_185 < Struct
  def key_id; end
  def key_id=(_); end
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
end
class Aws::KMS::Types::CancelKeyDeletionRequest < Anonymous_Struct_185
  include Aws::Structure
end
class Anonymous_Struct_186 < Struct
  def key_id; end
  def key_id=(_); end
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
end
class Aws::KMS::Types::CancelKeyDeletionResponse < Anonymous_Struct_186
  include Aws::Structure
end
class Anonymous_Struct_187 < Struct
  def message; end
  def message=(_); end
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
end
class Aws::KMS::Types::CloudHsmClusterInUseException < Anonymous_Struct_187
  include Aws::Structure
end
class Anonymous_Struct_188 < Struct
  def message; end
  def message=(_); end
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
end
class Aws::KMS::Types::CloudHsmClusterInvalidConfigurationException < Anonymous_Struct_188
  include Aws::Structure
end
class Anonymous_Struct_189 < Struct
  def message; end
  def message=(_); end
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
end
class Aws::KMS::Types::CloudHsmClusterNotActiveException < Anonymous_Struct_189
  include Aws::Structure
end
class Anonymous_Struct_190 < Struct
  def message; end
  def message=(_); end
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
end
class Aws::KMS::Types::CloudHsmClusterNotFoundException < Anonymous_Struct_190
  include Aws::Structure
end
class Anonymous_Struct_191 < Struct
  def message; end
  def message=(_); end
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
end
class Aws::KMS::Types::CloudHsmClusterNotRelatedException < Anonymous_Struct_191
  include Aws::Structure
end
class Anonymous_Struct_192 < Struct
  def custom_key_store_id; end
  def custom_key_store_id=(_); end
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
end
class Aws::KMS::Types::ConnectCustomKeyStoreRequest < Anonymous_Struct_192
  include Aws::Structure
end
class Aws::KMS::Types::ConnectCustomKeyStoreResponse < Aws::EmptyStructure
end
class Anonymous_Struct_193 < Struct
  def alias_name; end
  def alias_name=(_); end
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
  def target_key_id; end
  def target_key_id=(_); end
end
class Aws::KMS::Types::CreateAliasRequest < Anonymous_Struct_193
  include Aws::Structure
end
class Anonymous_Struct_194 < Struct
  def cloud_hsm_cluster_id; end
  def cloud_hsm_cluster_id=(_); end
  def custom_key_store_name; end
  def custom_key_store_name=(_); end
  def key_store_password; end
  def key_store_password=(_); end
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
  def trust_anchor_certificate; end
  def trust_anchor_certificate=(_); end
end
class Aws::KMS::Types::CreateCustomKeyStoreRequest < Anonymous_Struct_194
  include Aws::Structure
end
class Anonymous_Struct_195 < Struct
  def custom_key_store_id; end
  def custom_key_store_id=(_); end
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
end
class Aws::KMS::Types::CreateCustomKeyStoreResponse < Anonymous_Struct_195
  include Aws::Structure
end
class Anonymous_Struct_196 < Struct
  def constraints; end
  def constraints=(_); end
  def grant_tokens; end
  def grant_tokens=(_); end
  def grantee_principal; end
  def grantee_principal=(_); end
  def key_id; end
  def key_id=(_); end
  def name; end
  def name=(_); end
  def operations; end
  def operations=(_); end
  def retiring_principal; end
  def retiring_principal=(_); end
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
end
class Aws::KMS::Types::CreateGrantRequest < Anonymous_Struct_196
  include Aws::Structure
end
class Anonymous_Struct_197 < Struct
  def grant_id; end
  def grant_id=(_); end
  def grant_token; end
  def grant_token=(_); end
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
end
class Aws::KMS::Types::CreateGrantResponse < Anonymous_Struct_197
  include Aws::Structure
end
class Anonymous_Struct_198 < Struct
  def bypass_policy_lockout_safety_check; end
  def bypass_policy_lockout_safety_check=(_); end
  def custom_key_store_id; end
  def custom_key_store_id=(_); end
  def description; end
  def description=(_); end
  def key_usage; end
  def key_usage=(_); end
  def origin; end
  def origin=(_); end
  def policy; end
  def policy=(_); end
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
  def tags; end
  def tags=(_); end
end
class Aws::KMS::Types::CreateKeyRequest < Anonymous_Struct_198
  include Aws::Structure
end
class Anonymous_Struct_199 < Struct
  def key_metadata; end
  def key_metadata=(_); end
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
end
class Aws::KMS::Types::CreateKeyResponse < Anonymous_Struct_199
  include Aws::Structure
end
class Anonymous_Struct_200 < Struct
  def message; end
  def message=(_); end
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
end
class Aws::KMS::Types::CustomKeyStoreHasCMKsException < Anonymous_Struct_200
  include Aws::Structure
end
class Anonymous_Struct_201 < Struct
  def message; end
  def message=(_); end
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
end
class Aws::KMS::Types::CustomKeyStoreInvalidStateException < Anonymous_Struct_201
  include Aws::Structure
end
class Anonymous_Struct_202 < Struct
  def message; end
  def message=(_); end
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
end
class Aws::KMS::Types::CustomKeyStoreNameInUseException < Anonymous_Struct_202
  include Aws::Structure
end
class Anonymous_Struct_203 < Struct
  def message; end
  def message=(_); end
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
end
class Aws::KMS::Types::CustomKeyStoreNotFoundException < Anonymous_Struct_203
  include Aws::Structure
end
class Anonymous_Struct_204 < Struct
  def cloud_hsm_cluster_id; end
  def cloud_hsm_cluster_id=(_); end
  def connection_error_code; end
  def connection_error_code=(_); end
  def connection_state; end
  def connection_state=(_); end
  def creation_date; end
  def creation_date=(_); end
  def custom_key_store_id; end
  def custom_key_store_id=(_); end
  def custom_key_store_name; end
  def custom_key_store_name=(_); end
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
  def trust_anchor_certificate; end
  def trust_anchor_certificate=(_); end
end
class Aws::KMS::Types::CustomKeyStoresListEntry < Anonymous_Struct_204
  include Aws::Structure
end
class Anonymous_Struct_205 < Struct
  def ciphertext_blob; end
  def ciphertext_blob=(_); end
  def encryption_context; end
  def encryption_context=(_); end
  def grant_tokens; end
  def grant_tokens=(_); end
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
end
class Aws::KMS::Types::DecryptRequest < Anonymous_Struct_205
  include Aws::Structure
end
class Anonymous_Struct_206 < Struct
  def key_id; end
  def key_id=(_); end
  def plaintext; end
  def plaintext=(_); end
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
end
class Aws::KMS::Types::DecryptResponse < Anonymous_Struct_206
  include Aws::Structure
end
class Anonymous_Struct_207 < Struct
  def alias_name; end
  def alias_name=(_); end
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
end
class Aws::KMS::Types::DeleteAliasRequest < Anonymous_Struct_207
  include Aws::Structure
end
class Anonymous_Struct_208 < Struct
  def custom_key_store_id; end
  def custom_key_store_id=(_); end
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
end
class Aws::KMS::Types::DeleteCustomKeyStoreRequest < Anonymous_Struct_208
  include Aws::Structure
end
class Aws::KMS::Types::DeleteCustomKeyStoreResponse < Aws::EmptyStructure
end
class Anonymous_Struct_209 < Struct
  def key_id; end
  def key_id=(_); end
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
end
class Aws::KMS::Types::DeleteImportedKeyMaterialRequest < Anonymous_Struct_209
  include Aws::Structure
end
class Anonymous_Struct_210 < Struct
  def message; end
  def message=(_); end
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
end
class Aws::KMS::Types::DependencyTimeoutException < Anonymous_Struct_210
  include Aws::Structure
end
class Anonymous_Struct_211 < Struct
  def custom_key_store_id; end
  def custom_key_store_id=(_); end
  def custom_key_store_name; end
  def custom_key_store_name=(_); end
  def limit; end
  def limit=(_); end
  def marker; end
  def marker=(_); end
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
end
class Aws::KMS::Types::DescribeCustomKeyStoresRequest < Anonymous_Struct_211
  include Aws::Structure
end
class Anonymous_Struct_212 < Struct
  def custom_key_stores; end
  def custom_key_stores=(_); end
  def next_marker; end
  def next_marker=(_); end
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
  def truncated; end
  def truncated=(_); end
end
class Aws::KMS::Types::DescribeCustomKeyStoresResponse < Anonymous_Struct_212
  include Aws::Structure
end
class Anonymous_Struct_213 < Struct
  def grant_tokens; end
  def grant_tokens=(_); end
  def key_id; end
  def key_id=(_); end
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
end
class Aws::KMS::Types::DescribeKeyRequest < Anonymous_Struct_213
  include Aws::Structure
end
class Anonymous_Struct_214 < Struct
  def key_metadata; end
  def key_metadata=(_); end
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
end
class Aws::KMS::Types::DescribeKeyResponse < Anonymous_Struct_214
  include Aws::Structure
end
class Anonymous_Struct_215 < Struct
  def key_id; end
  def key_id=(_); end
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
end
class Aws::KMS::Types::DisableKeyRequest < Anonymous_Struct_215
  include Aws::Structure
end
class Anonymous_Struct_216 < Struct
  def key_id; end
  def key_id=(_); end
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
end
class Aws::KMS::Types::DisableKeyRotationRequest < Anonymous_Struct_216
  include Aws::Structure
end
class Anonymous_Struct_217 < Struct
  def message; end
  def message=(_); end
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
end
class Aws::KMS::Types::DisabledException < Anonymous_Struct_217
  include Aws::Structure
end
class Anonymous_Struct_218 < Struct
  def custom_key_store_id; end
  def custom_key_store_id=(_); end
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
end
class Aws::KMS::Types::DisconnectCustomKeyStoreRequest < Anonymous_Struct_218
  include Aws::Structure
end
class Aws::KMS::Types::DisconnectCustomKeyStoreResponse < Aws::EmptyStructure
end
class Anonymous_Struct_219 < Struct
  def key_id; end
  def key_id=(_); end
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
end
class Aws::KMS::Types::EnableKeyRequest < Anonymous_Struct_219
  include Aws::Structure
end
class Anonymous_Struct_220 < Struct
  def key_id; end
  def key_id=(_); end
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
end
class Aws::KMS::Types::EnableKeyRotationRequest < Anonymous_Struct_220
  include Aws::Structure
end
class Anonymous_Struct_221 < Struct
  def encryption_context; end
  def encryption_context=(_); end
  def grant_tokens; end
  def grant_tokens=(_); end
  def key_id; end
  def key_id=(_); end
  def plaintext; end
  def plaintext=(_); end
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
end
class Aws::KMS::Types::EncryptRequest < Anonymous_Struct_221
  include Aws::Structure
end
class Anonymous_Struct_222 < Struct
  def ciphertext_blob; end
  def ciphertext_blob=(_); end
  def key_id; end
  def key_id=(_); end
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
end
class Aws::KMS::Types::EncryptResponse < Anonymous_Struct_222
  include Aws::Structure
end
class Anonymous_Struct_223 < Struct
  def message; end
  def message=(_); end
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
end
class Aws::KMS::Types::ExpiredImportTokenException < Anonymous_Struct_223
  include Aws::Structure
end
class Anonymous_Struct_224 < Struct
  def encryption_context; end
  def encryption_context=(_); end
  def grant_tokens; end
  def grant_tokens=(_); end
  def key_id; end
  def key_id=(_); end
  def key_spec; end
  def key_spec=(_); end
  def number_of_bytes; end
  def number_of_bytes=(_); end
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
end
class Aws::KMS::Types::GenerateDataKeyRequest < Anonymous_Struct_224
  include Aws::Structure
end
class Anonymous_Struct_225 < Struct
  def ciphertext_blob; end
  def ciphertext_blob=(_); end
  def key_id; end
  def key_id=(_); end
  def plaintext; end
  def plaintext=(_); end
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
end
class Aws::KMS::Types::GenerateDataKeyResponse < Anonymous_Struct_225
  include Aws::Structure
end
class Anonymous_Struct_226 < Struct
  def encryption_context; end
  def encryption_context=(_); end
  def grant_tokens; end
  def grant_tokens=(_); end
  def key_id; end
  def key_id=(_); end
  def key_spec; end
  def key_spec=(_); end
  def number_of_bytes; end
  def number_of_bytes=(_); end
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
end
class Aws::KMS::Types::GenerateDataKeyWithoutPlaintextRequest < Anonymous_Struct_226
  include Aws::Structure
end
class Anonymous_Struct_227 < Struct
  def ciphertext_blob; end
  def ciphertext_blob=(_); end
  def key_id; end
  def key_id=(_); end
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
end
class Aws::KMS::Types::GenerateDataKeyWithoutPlaintextResponse < Anonymous_Struct_227
  include Aws::Structure
end
class Anonymous_Struct_228 < Struct
  def custom_key_store_id; end
  def custom_key_store_id=(_); end
  def number_of_bytes; end
  def number_of_bytes=(_); end
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
end
class Aws::KMS::Types::GenerateRandomRequest < Anonymous_Struct_228
  include Aws::Structure
end
class Anonymous_Struct_229 < Struct
  def plaintext; end
  def plaintext=(_); end
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
end
class Aws::KMS::Types::GenerateRandomResponse < Anonymous_Struct_229
  include Aws::Structure
end
class Anonymous_Struct_230 < Struct
  def key_id; end
  def key_id=(_); end
  def policy_name; end
  def policy_name=(_); end
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
end
class Aws::KMS::Types::GetKeyPolicyRequest < Anonymous_Struct_230
  include Aws::Structure
end
class Anonymous_Struct_231 < Struct
  def policy; end
  def policy=(_); end
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
end
class Aws::KMS::Types::GetKeyPolicyResponse < Anonymous_Struct_231
  include Aws::Structure
end
class Anonymous_Struct_232 < Struct
  def key_id; end
  def key_id=(_); end
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
end
class Aws::KMS::Types::GetKeyRotationStatusRequest < Anonymous_Struct_232
  include Aws::Structure
end
class Anonymous_Struct_233 < Struct
  def key_rotation_enabled; end
  def key_rotation_enabled=(_); end
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
end
class Aws::KMS::Types::GetKeyRotationStatusResponse < Anonymous_Struct_233
  include Aws::Structure
end
class Anonymous_Struct_234 < Struct
  def key_id; end
  def key_id=(_); end
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
  def wrapping_algorithm; end
  def wrapping_algorithm=(_); end
  def wrapping_key_spec; end
  def wrapping_key_spec=(_); end
end
class Aws::KMS::Types::GetParametersForImportRequest < Anonymous_Struct_234
  include Aws::Structure
end
class Anonymous_Struct_235 < Struct
  def import_token; end
  def import_token=(_); end
  def key_id; end
  def key_id=(_); end
  def parameters_valid_to; end
  def parameters_valid_to=(_); end
  def public_key; end
  def public_key=(_); end
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
end
class Aws::KMS::Types::GetParametersForImportResponse < Anonymous_Struct_235
  include Aws::Structure
end
class Anonymous_Struct_236 < Struct
  def encryption_context_equals; end
  def encryption_context_equals=(_); end
  def encryption_context_subset; end
  def encryption_context_subset=(_); end
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
end
class Aws::KMS::Types::GrantConstraints < Anonymous_Struct_236
  include Aws::Structure
end
class Anonymous_Struct_237 < Struct
  def constraints; end
  def constraints=(_); end
  def creation_date; end
  def creation_date=(_); end
  def grant_id; end
  def grant_id=(_); end
  def grantee_principal; end
  def grantee_principal=(_); end
  def issuing_account; end
  def issuing_account=(_); end
  def key_id; end
  def key_id=(_); end
  def name; end
  def name=(_); end
  def operations; end
  def operations=(_); end
  def retiring_principal; end
  def retiring_principal=(_); end
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
end
class Aws::KMS::Types::GrantListEntry < Anonymous_Struct_237
  include Aws::Structure
end
class Anonymous_Struct_238 < Struct
  def encrypted_key_material; end
  def encrypted_key_material=(_); end
  def expiration_model; end
  def expiration_model=(_); end
  def import_token; end
  def import_token=(_); end
  def key_id; end
  def key_id=(_); end
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
  def valid_to; end
  def valid_to=(_); end
end
class Aws::KMS::Types::ImportKeyMaterialRequest < Anonymous_Struct_238
  include Aws::Structure
end
class Aws::KMS::Types::ImportKeyMaterialResponse < Aws::EmptyStructure
end
class Anonymous_Struct_239 < Struct
  def message; end
  def message=(_); end
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
end
class Aws::KMS::Types::IncorrectKeyMaterialException < Anonymous_Struct_239
  include Aws::Structure
end
class Anonymous_Struct_240 < Struct
  def message; end
  def message=(_); end
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
end
class Aws::KMS::Types::IncorrectTrustAnchorException < Anonymous_Struct_240
  include Aws::Structure
end
class Anonymous_Struct_241 < Struct
  def message; end
  def message=(_); end
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
end
class Aws::KMS::Types::InvalidAliasNameException < Anonymous_Struct_241
  include Aws::Structure
end
class Anonymous_Struct_242 < Struct
  def message; end
  def message=(_); end
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
end
class Aws::KMS::Types::InvalidArnException < Anonymous_Struct_242
  include Aws::Structure
end
class Anonymous_Struct_243 < Struct
  def message; end
  def message=(_); end
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
end
class Aws::KMS::Types::InvalidCiphertextException < Anonymous_Struct_243
  include Aws::Structure
end
class Anonymous_Struct_244 < Struct
  def message; end
  def message=(_); end
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
end
class Aws::KMS::Types::InvalidGrantIdException < Anonymous_Struct_244
  include Aws::Structure
end
class Anonymous_Struct_245 < Struct
  def message; end
  def message=(_); end
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
end
class Aws::KMS::Types::InvalidGrantTokenException < Anonymous_Struct_245
  include Aws::Structure
end
class Anonymous_Struct_246 < Struct
  def message; end
  def message=(_); end
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
end
class Aws::KMS::Types::InvalidImportTokenException < Anonymous_Struct_246
  include Aws::Structure
end
class Anonymous_Struct_247 < Struct
  def message; end
  def message=(_); end
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
end
class Aws::KMS::Types::InvalidKeyUsageException < Anonymous_Struct_247
  include Aws::Structure
end
class Anonymous_Struct_248 < Struct
  def message; end
  def message=(_); end
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
end
class Aws::KMS::Types::InvalidMarkerException < Anonymous_Struct_248
  include Aws::Structure
end
class Anonymous_Struct_249 < Struct
  def message; end
  def message=(_); end
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
end
class Aws::KMS::Types::KMSInternalException < Anonymous_Struct_249
  include Aws::Structure
end
class Anonymous_Struct_250 < Struct
  def message; end
  def message=(_); end
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
end
class Aws::KMS::Types::KMSInvalidStateException < Anonymous_Struct_250
  include Aws::Structure
end
class Anonymous_Struct_251 < Struct
  def key_arn; end
  def key_arn=(_); end
  def key_id; end
  def key_id=(_); end
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
end
class Aws::KMS::Types::KeyListEntry < Anonymous_Struct_251
  include Aws::Structure
end
class Anonymous_Struct_252 < Struct
  def arn; end
  def arn=(_); end
  def aws_account_id; end
  def aws_account_id=(_); end
  def cloud_hsm_cluster_id; end
  def cloud_hsm_cluster_id=(_); end
  def creation_date; end
  def creation_date=(_); end
  def custom_key_store_id; end
  def custom_key_store_id=(_); end
  def deletion_date; end
  def deletion_date=(_); end
  def description; end
  def description=(_); end
  def enabled; end
  def enabled=(_); end
  def expiration_model; end
  def expiration_model=(_); end
  def key_id; end
  def key_id=(_); end
  def key_manager; end
  def key_manager=(_); end
  def key_state; end
  def key_state=(_); end
  def key_usage; end
  def key_usage=(_); end
  def origin; end
  def origin=(_); end
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
  def valid_to; end
  def valid_to=(_); end
end
class Aws::KMS::Types::KeyMetadata < Anonymous_Struct_252
  include Aws::Structure
end
class Anonymous_Struct_253 < Struct
  def message; end
  def message=(_); end
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
end
class Aws::KMS::Types::KeyUnavailableException < Anonymous_Struct_253
  include Aws::Structure
end
class Anonymous_Struct_254 < Struct
  def message; end
  def message=(_); end
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
end
class Aws::KMS::Types::LimitExceededException < Anonymous_Struct_254
  include Aws::Structure
end
class Anonymous_Struct_255 < Struct
  def key_id; end
  def key_id=(_); end
  def limit; end
  def limit=(_); end
  def marker; end
  def marker=(_); end
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
end
class Aws::KMS::Types::ListAliasesRequest < Anonymous_Struct_255
  include Aws::Structure
end
class Anonymous_Struct_256 < Struct
  def aliases; end
  def aliases=(_); end
  def next_marker; end
  def next_marker=(_); end
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
  def truncated; end
  def truncated=(_); end
end
class Aws::KMS::Types::ListAliasesResponse < Anonymous_Struct_256
  include Aws::Structure
end
class Anonymous_Struct_257 < Struct
  def key_id; end
  def key_id=(_); end
  def limit; end
  def limit=(_); end
  def marker; end
  def marker=(_); end
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
end
class Aws::KMS::Types::ListGrantsRequest < Anonymous_Struct_257
  include Aws::Structure
end
class Anonymous_Struct_258 < Struct
  def grants; end
  def grants=(_); end
  def next_marker; end
  def next_marker=(_); end
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
  def truncated; end
  def truncated=(_); end
end
class Aws::KMS::Types::ListGrantsResponse < Anonymous_Struct_258
  include Aws::Structure
end
class Anonymous_Struct_259 < Struct
  def key_id; end
  def key_id=(_); end
  def limit; end
  def limit=(_); end
  def marker; end
  def marker=(_); end
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
end
class Aws::KMS::Types::ListKeyPoliciesRequest < Anonymous_Struct_259
  include Aws::Structure
end
class Anonymous_Struct_260 < Struct
  def next_marker; end
  def next_marker=(_); end
  def policy_names; end
  def policy_names=(_); end
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
  def truncated; end
  def truncated=(_); end
end
class Aws::KMS::Types::ListKeyPoliciesResponse < Anonymous_Struct_260
  include Aws::Structure
end
class Anonymous_Struct_261 < Struct
  def limit; end
  def limit=(_); end
  def marker; end
  def marker=(_); end
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
end
class Aws::KMS::Types::ListKeysRequest < Anonymous_Struct_261
  include Aws::Structure
end
class Anonymous_Struct_262 < Struct
  def keys; end
  def keys=(_); end
  def next_marker; end
  def next_marker=(_); end
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
  def truncated; end
  def truncated=(_); end
end
class Aws::KMS::Types::ListKeysResponse < Anonymous_Struct_262
  include Aws::Structure
end
class Anonymous_Struct_263 < Struct
  def key_id; end
  def key_id=(_); end
  def limit; end
  def limit=(_); end
  def marker; end
  def marker=(_); end
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
end
class Aws::KMS::Types::ListResourceTagsRequest < Anonymous_Struct_263
  include Aws::Structure
end
class Anonymous_Struct_264 < Struct
  def next_marker; end
  def next_marker=(_); end
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
  def tags; end
  def tags=(_); end
  def truncated; end
  def truncated=(_); end
end
class Aws::KMS::Types::ListResourceTagsResponse < Anonymous_Struct_264
  include Aws::Structure
end
class Anonymous_Struct_265 < Struct
  def limit; end
  def limit=(_); end
  def marker; end
  def marker=(_); end
  def retiring_principal; end
  def retiring_principal=(_); end
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
end
class Aws::KMS::Types::ListRetirableGrantsRequest < Anonymous_Struct_265
  include Aws::Structure
end
class Anonymous_Struct_266 < Struct
  def message; end
  def message=(_); end
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
end
class Aws::KMS::Types::MalformedPolicyDocumentException < Anonymous_Struct_266
  include Aws::Structure
end
class Anonymous_Struct_267 < Struct
  def message; end
  def message=(_); end
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
end
class Aws::KMS::Types::NotFoundException < Anonymous_Struct_267
  include Aws::Structure
end
class Anonymous_Struct_268 < Struct
  def bypass_policy_lockout_safety_check; end
  def bypass_policy_lockout_safety_check=(_); end
  def key_id; end
  def key_id=(_); end
  def policy; end
  def policy=(_); end
  def policy_name; end
  def policy_name=(_); end
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
end
class Aws::KMS::Types::PutKeyPolicyRequest < Anonymous_Struct_268
  include Aws::Structure
end
class Anonymous_Struct_269 < Struct
  def ciphertext_blob; end
  def ciphertext_blob=(_); end
  def destination_encryption_context; end
  def destination_encryption_context=(_); end
  def destination_key_id; end
  def destination_key_id=(_); end
  def grant_tokens; end
  def grant_tokens=(_); end
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
  def source_encryption_context; end
  def source_encryption_context=(_); end
end
class Aws::KMS::Types::ReEncryptRequest < Anonymous_Struct_269
  include Aws::Structure
end
class Anonymous_Struct_270 < Struct
  def ciphertext_blob; end
  def ciphertext_blob=(_); end
  def key_id; end
  def key_id=(_); end
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
  def source_key_id; end
  def source_key_id=(_); end
end
class Aws::KMS::Types::ReEncryptResponse < Anonymous_Struct_270
  include Aws::Structure
end
class Anonymous_Struct_271 < Struct
  def grant_id; end
  def grant_id=(_); end
  def grant_token; end
  def grant_token=(_); end
  def key_id; end
  def key_id=(_); end
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
end
class Aws::KMS::Types::RetireGrantRequest < Anonymous_Struct_271
  include Aws::Structure
end
class Anonymous_Struct_272 < Struct
  def grant_id; end
  def grant_id=(_); end
  def key_id; end
  def key_id=(_); end
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
end
class Aws::KMS::Types::RevokeGrantRequest < Anonymous_Struct_272
  include Aws::Structure
end
class Anonymous_Struct_273 < Struct
  def key_id; end
  def key_id=(_); end
  def pending_window_in_days; end
  def pending_window_in_days=(_); end
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
end
class Aws::KMS::Types::ScheduleKeyDeletionRequest < Anonymous_Struct_273
  include Aws::Structure
end
class Anonymous_Struct_274 < Struct
  def deletion_date; end
  def deletion_date=(_); end
  def key_id; end
  def key_id=(_); end
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
end
class Aws::KMS::Types::ScheduleKeyDeletionResponse < Anonymous_Struct_274
  include Aws::Structure
end
class Anonymous_Struct_275 < Struct
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
  def tag_key; end
  def tag_key=(_); end
  def tag_value; end
  def tag_value=(_); end
end
class Aws::KMS::Types::Tag < Anonymous_Struct_275
  include Aws::Structure
end
class Anonymous_Struct_276 < Struct
  def message; end
  def message=(_); end
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
end
class Aws::KMS::Types::TagException < Anonymous_Struct_276
  include Aws::Structure
end
class Anonymous_Struct_277 < Struct
  def key_id; end
  def key_id=(_); end
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
  def tags; end
  def tags=(_); end
end
class Aws::KMS::Types::TagResourceRequest < Anonymous_Struct_277
  include Aws::Structure
end
class Anonymous_Struct_278 < Struct
  def message; end
  def message=(_); end
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
end
class Aws::KMS::Types::UnsupportedOperationException < Anonymous_Struct_278
  include Aws::Structure
end
class Anonymous_Struct_279 < Struct
  def key_id; end
  def key_id=(_); end
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
  def tag_keys; end
  def tag_keys=(_); end
end
class Aws::KMS::Types::UntagResourceRequest < Anonymous_Struct_279
  include Aws::Structure
end
class Anonymous_Struct_280 < Struct
  def alias_name; end
  def alias_name=(_); end
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
  def target_key_id; end
  def target_key_id=(_); end
end
class Aws::KMS::Types::UpdateAliasRequest < Anonymous_Struct_280
  include Aws::Structure
end
class Anonymous_Struct_281 < Struct
  def cloud_hsm_cluster_id; end
  def cloud_hsm_cluster_id=(_); end
  def custom_key_store_id; end
  def custom_key_store_id=(_); end
  def key_store_password; end
  def key_store_password=(_); end
  def new_custom_key_store_name; end
  def new_custom_key_store_name=(_); end
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
end
class Aws::KMS::Types::UpdateCustomKeyStoreRequest < Anonymous_Struct_281
  include Aws::Structure
end
class Aws::KMS::Types::UpdateCustomKeyStoreResponse < Aws::EmptyStructure
end
class Anonymous_Struct_282 < Struct
  def description; end
  def description=(_); end
  def key_id; end
  def key_id=(_); end
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
end
class Aws::KMS::Types::UpdateKeyDescriptionRequest < Anonymous_Struct_282
  include Aws::Structure
end
module Aws::KMS::ClientApi
  include Seahorse::Model
end
class Aws::KMS::Client < Seahorse::Client::Base
  def build_request(operation_name, params = nil); end
  def cancel_key_deletion(params = nil, options = nil); end
  def connect_custom_key_store(params = nil, options = nil); end
  def create_alias(params = nil, options = nil); end
  def create_custom_key_store(params = nil, options = nil); end
  def create_grant(params = nil, options = nil); end
  def create_key(params = nil, options = nil); end
  def decrypt(params = nil, options = nil); end
  def delete_alias(params = nil, options = nil); end
  def delete_custom_key_store(params = nil, options = nil); end
  def delete_imported_key_material(params = nil, options = nil); end
  def describe_custom_key_stores(params = nil, options = nil); end
  def describe_key(params = nil, options = nil); end
  def disable_key(params = nil, options = nil); end
  def disable_key_rotation(params = nil, options = nil); end
  def disconnect_custom_key_store(params = nil, options = nil); end
  def enable_key(params = nil, options = nil); end
  def enable_key_rotation(params = nil, options = nil); end
  def encrypt(params = nil, options = nil); end
  def generate_data_key(params = nil, options = nil); end
  def generate_data_key_without_plaintext(params = nil, options = nil); end
  def generate_random(params = nil, options = nil); end
  def get_key_policy(params = nil, options = nil); end
  def get_key_rotation_status(params = nil, options = nil); end
  def get_parameters_for_import(params = nil, options = nil); end
  def import_key_material(params = nil, options = nil); end
  def initialize(*args); end
  def list_aliases(params = nil, options = nil); end
  def list_grants(params = nil, options = nil); end
  def list_key_policies(params = nil, options = nil); end
  def list_keys(params = nil, options = nil); end
  def list_resource_tags(params = nil, options = nil); end
  def list_retirable_grants(params = nil, options = nil); end
  def put_key_policy(params = nil, options = nil); end
  def re_encrypt(params = nil, options = nil); end
  def retire_grant(params = nil, options = nil); end
  def revoke_grant(params = nil, options = nil); end
  def schedule_key_deletion(params = nil, options = nil); end
  def self.errors_module; end
  def self.identifier; end
  def tag_resource(params = nil, options = nil); end
  def untag_resource(params = nil, options = nil); end
  def update_alias(params = nil, options = nil); end
  def update_custom_key_store(params = nil, options = nil); end
  def update_key_description(params = nil, options = nil); end
  def waiter_names; end
  include Aws::ClientStubs
end
module Aws::KMS::Errors
  extend Aws::Errors::DynamicErrors
end
class Aws::KMS::Errors::ServiceError < Aws::Errors::ServiceError
end
class Aws::KMS::Errors::AlreadyExistsException < Aws::KMS::Errors::ServiceError
  def initialize(context, message, data = nil); end
  def message; end
end
class Aws::KMS::Errors::CloudHsmClusterInUseException < Aws::KMS::Errors::ServiceError
  def initialize(context, message, data = nil); end
  def message; end
end
class Aws::KMS::Errors::CloudHsmClusterInvalidConfigurationException < Aws::KMS::Errors::ServiceError
  def initialize(context, message, data = nil); end
  def message; end
end
class Aws::KMS::Errors::CloudHsmClusterNotActiveException < Aws::KMS::Errors::ServiceError
  def initialize(context, message, data = nil); end
  def message; end
end
class Aws::KMS::Errors::CloudHsmClusterNotFoundException < Aws::KMS::Errors::ServiceError
  def initialize(context, message, data = nil); end
  def message; end
end
class Aws::KMS::Errors::CloudHsmClusterNotRelatedException < Aws::KMS::Errors::ServiceError
  def initialize(context, message, data = nil); end
  def message; end
end
class Aws::KMS::Errors::CustomKeyStoreHasCMKsException < Aws::KMS::Errors::ServiceError
  def initialize(context, message, data = nil); end
  def message; end
end
class Aws::KMS::Errors::CustomKeyStoreInvalidStateException < Aws::KMS::Errors::ServiceError
  def initialize(context, message, data = nil); end
  def message; end
end
class Aws::KMS::Errors::CustomKeyStoreNameInUseException < Aws::KMS::Errors::ServiceError
  def initialize(context, message, data = nil); end
  def message; end
end
class Aws::KMS::Errors::CustomKeyStoreNotFoundException < Aws::KMS::Errors::ServiceError
  def initialize(context, message, data = nil); end
  def message; end
end
class Aws::KMS::Errors::DependencyTimeoutException < Aws::KMS::Errors::ServiceError
  def initialize(context, message, data = nil); end
  def message; end
end
class Aws::KMS::Errors::DisabledException < Aws::KMS::Errors::ServiceError
  def initialize(context, message, data = nil); end
  def message; end
end
class Aws::KMS::Errors::ExpiredImportTokenException < Aws::KMS::Errors::ServiceError
  def initialize(context, message, data = nil); end
  def message; end
end
class Aws::KMS::Errors::IncorrectKeyMaterialException < Aws::KMS::Errors::ServiceError
  def initialize(context, message, data = nil); end
  def message; end
end
class Aws::KMS::Errors::IncorrectTrustAnchorException < Aws::KMS::Errors::ServiceError
  def initialize(context, message, data = nil); end
  def message; end
end
class Aws::KMS::Errors::InvalidAliasNameException < Aws::KMS::Errors::ServiceError
  def initialize(context, message, data = nil); end
  def message; end
end
class Aws::KMS::Errors::InvalidArnException < Aws::KMS::Errors::ServiceError
  def initialize(context, message, data = nil); end
  def message; end
end
class Aws::KMS::Errors::InvalidCiphertextException < Aws::KMS::Errors::ServiceError
  def initialize(context, message, data = nil); end
  def message; end
end
class Aws::KMS::Errors::InvalidGrantIdException < Aws::KMS::Errors::ServiceError
  def initialize(context, message, data = nil); end
  def message; end
end
class Aws::KMS::Errors::InvalidGrantTokenException < Aws::KMS::Errors::ServiceError
  def initialize(context, message, data = nil); end
  def message; end
end
class Aws::KMS::Errors::InvalidImportTokenException < Aws::KMS::Errors::ServiceError
  def initialize(context, message, data = nil); end
  def message; end
end
class Aws::KMS::Errors::InvalidKeyUsageException < Aws::KMS::Errors::ServiceError
  def initialize(context, message, data = nil); end
  def message; end
end
class Aws::KMS::Errors::InvalidMarkerException < Aws::KMS::Errors::ServiceError
  def initialize(context, message, data = nil); end
  def message; end
end
class Aws::KMS::Errors::KMSInternalException < Aws::KMS::Errors::ServiceError
  def initialize(context, message, data = nil); end
  def message; end
end
class Aws::KMS::Errors::KMSInvalidStateException < Aws::KMS::Errors::ServiceError
  def initialize(context, message, data = nil); end
  def message; end
end
class Aws::KMS::Errors::KeyUnavailableException < Aws::KMS::Errors::ServiceError
  def initialize(context, message, data = nil); end
  def message; end
end
class Aws::KMS::Errors::LimitExceededException < Aws::KMS::Errors::ServiceError
  def initialize(context, message, data = nil); end
  def message; end
end
class Aws::KMS::Errors::MalformedPolicyDocumentException < Aws::KMS::Errors::ServiceError
  def initialize(context, message, data = nil); end
  def message; end
end
class Aws::KMS::Errors::NotFoundException < Aws::KMS::Errors::ServiceError
  def initialize(context, message, data = nil); end
  def message; end
end
class Aws::KMS::Errors::TagException < Aws::KMS::Errors::ServiceError
  def initialize(context, message, data = nil); end
  def message; end
end
class Aws::KMS::Errors::UnsupportedOperationException < Aws::KMS::Errors::ServiceError
  def initialize(context, message, data = nil); end
  def message; end
end
class Aws::KMS::Resource
  def client; end
  def initialize(options = nil); end
end
